name: Deploy a subset of management groups using an SPN
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-management-groups:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/login@v1
        name: Azure OIDC login
        with:         
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
      
      - uses: azure/powershell@v1
        name: Reading all MGs
        with:
          inlineScript: |
            Get-AzManagementGroup
          azPSVersion: "latest"

      - uses: azure/powershell@v1
        name: Performing a tenant deployment
        with:
          inlineScript: |
            New-AzTenantDeployment -Location "westeurope" -TemplateFile "arm-templates/management-group.template.json"
          azPSVersion: "latest"