name: Deprovision all the Azure Resources created during the Hackathon
on:
  workflow_dispatch:

jobs:
  stop-all-azure-vms:
    uses: ./.github/workflows/stop-all-virtual-machines.yml
    secrets: inherit
  remove-all-resource-groups:
    needs: stop-all-azure-vms
    uses: ./.github/workflows/remove-all-resource-groups.yml
    secrets: inherit
  remove-all-external-users:
    uses: ./.github/workflows/remove-all-hackathon-participants.yml
    secrets: inherit