name: Hackathon Provisioning
on:
  workflow_dispatch:

jobs:
  provision-users-and-groups:
    uses: ./.github/workflows/provision-all-users-and-groups.yml
    secrets: inherit

  provision-management-groups-and-subscriptions:
    needs: provision-users-and-groups
    uses: ./.github/workflows/provision-all-management-groups-and-subscriptions.yml
    secrets: inherit