name: Remove All Hackathon Participants from the tenant

on:
    workflow_call:
    workflow_dispatch:

jobs:
    remove-all-rgs:
        runs-on: [self-hosted, linux]
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v2

            - uses: azure/login@v1
              name: Azure OIDC login
              with:         
                    tenant-id: ${{ secrets.TENANT_ID }}
                    client-id: ${{ secrets.CLIENT_ID }}
                    allow-no-subscriptions: true
                    enable-AzPSSession: true
            
            - shell: pwsh
              name: Remove All Hackathon Participants from the tenant
              run: |
                ./scripts/remove-all-hackathon-participants.ps1